cache: bundler
language: ruby

rvm:
  - 2.6.6
  - 2.7.2
  - 3.0.0

before_install:
  - gem install bundler -v 2.2.3

gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
