sudo: false
cache: bundler
language: ruby

rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile

install:
  - bundle install --jobs=3 --retry=3
  - bundle exec appraisal install

script:
  - bundle exec appraisal rake
